# syntax=docker/dockerfile:1.4

# Base image with Python 3.13
FROM python:3.13-slim

# Install system dependencies for geospatial libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    gdal-bin \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libspatialindex-dev \
    gcc \
    g++ \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install uv for fast package management
COPY --from=ghcr.io/astral-sh/uv:0.4.20 /uv /bin/uv
ENV UV_SYSTEM_PYTHON=1

WORKDIR /app

# Copy dependency files
COPY --link pyproject.toml .

# Install Python dependencies using uv
RUN uv pip install -e .

# Copy application files
COPY --link predict_map.py .

# Copy model files (generated by running accident_fetch_data.py)
COPY --link accident_model.pkl atm_encoder.pkl features.pkl routes.nc ./

# Expose port 8080
EXPOSE 8080

# Create non-root user
RUN useradd -m app_user && chown -R app_user:app_user /app
USER app_user

# Health check
HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:8080/health || exit 1

# Run the marimo app
CMD ["marimo", "run", "predict_map.py", "--host", "0.0.0.0", "-p", "8080"]
